import streamlit as st
import db
from datetime import datetime


def render():
    st.markdown("## 📄 Reports")
    st.caption("One-click, downloadable per-state land-governance intelligence briefs.")

    records = db.get_land_records()
    state = st.selectbox("Select a state", sorted(records["state"].unique().tolist()))
    row = records[records["state"] == state].iloc[0]

    st.markdown("#### Preview")
    with st.container(border=True):
        st.markdown(f"**{state} — Land Governance Brief**")
        st.write(f"Region: {row['region']}")
        st.write(f"Risk score: **{row['risk_score']:.0f}** / 100")
        st.write(f"Recorded land disputes: **{int(row['land_disputes'])}**")
        st.write(f"Total land parcels: **{int(row['total_parcels']):,}**")
        st.write(
            f"Land use — Agricultural: {row['agricultural_pct']}%, "
            f"Forest: {row['forest_pct']}%, Urban: {row['urban_pct']}%, "
            f"Wasteland: {row['wasteland_pct']}%, Water: {row['water_pct']}%"
        )

    report_text = f"""BHUMI-INSIGHT — LAND GOVERNANCE INTELLIGENCE BRIEF
State: {state}
Region: {row['region']}
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}
Generated by: {st.session_state.user['name']} ({st.session_state.role})

SUMMARY
-------
Risk score: {row['risk_score']:.0f} / 100
Recorded land disputes: {int(row['land_disputes'])}
Total land parcels: {int(row['total_parcels']):,}

LAND USE BREAKDOWN
-------------------
Agricultural: {row['agricultural_pct']}%
Forest: {row['forest_pct']}%
Urban: {row['urban_pct']}%
Wasteland: {row['wasteland_pct']}%
Water bodies: {row['water_pct']}%

NOTE
----
This brief is generated from synthetic demo data for prototype/
demonstration purposes only and does not reflect official government
statistics.
"""

    st.download_button(
        "⬇ Download Report (.txt)",
        data=report_text,
        file_name=f"{state.replace(' ', '_')}_brief.txt",
        mime="text/plain",
    )

    st.markdown("#### All States — Risk Overview")
    st.dataframe(
        records[["state", "region", "risk_score", "land_disputes", "total_parcels"]].sort_values(
            "risk_score", ascending=False
        ),
        use_container_width=True,
        hide_index=True,
    )
